#! /usr/bin/ruby

$: << File.join(File.dirname($0), "lib")

require 'ncurses'
require 'mmap'
require 'cless'

data = MapData.new(ARGV[0])

curses_init
at_exit { curses_close }

$log = File.open("log", "w")
$log.sync = true

begin
  loop do
    display_lines(data)
    Ncurses.move(Ncurses.stdscr.getmaxy-1, 0)
    Ncurses.addstr(data.debug)
    wait_for_key(data) or break
  end
rescue Exception => e
  Ncurses.endwin
  puts("#{e.message} (#{e.class}): #{e.backtrace.join("\n")}")
end
